config/routes.rb
RssReader::Application.routes.draw do

  root 'feeds#index'

  resources :feeds do
    collection do
      get "readers"
    end
  end

end

app/models/feed.rb
require "rss_reader"
class Feed < ActiveRecord::Base
  include RssReader
  attr_accessible :feed_url
  attr_protected :title, :url, :description
  attr_accessor :entries
  
  validates :feed_url, presence: true, uniqueness: true
  
  before_validation do
    self.title, self.url, self.description = fetch_feed(self.feed_url)
    errors.add(:base, "Invalid feed url!") unless self.title
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/feeds_controller.rb
require "rss_reader"
class FeedsController < ApplicationController
  include RssReader

  # GET /feeds
  # GET /feeds.json
  def index
    @feeds = Feed.order(:title).page(params[:page]).per(5)
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feeds }
    end
  end
  
  # GET /feeds/readers
  # GET /feeds/readers.json
  def readers
    @posts = fetch_feeds(Feed.all.collect { |f| f.feed_url })
    respond_to do |format|
      format.html # readers.html.erb
      format.json { render json: @posts }
    end
  end
  
  # GET /feeds/new
  # GET /feeds/new.json
  def new
    @feed = Feed.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feed }
    end
  end
  
  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.new(feed_params)
    if @feed.save
      respond_to do |format|
        format.html { redirect_to @feed, notice: 'Successfully created.' }
        format.json { render json: @feed, status: :created, location: @feed }
      end
    else
      respond_to do |format|
        format.html { render action: "new" }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # GET /feeds/1
  # GET /feeds/1.json
  def show
    @feed = Feed.find(params[:id])
    @feed.entries = Feedzirra::Feed.fetch_and_parse(@feed.feed_url).entries rescue nil

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feed }
    end
  end
  
  # GET /feeds/1/edit
  # GET /feeds/1/edit.json
  def edit
    @feed = Feed.find(params[:id])
  end
  
  # PUT  /feeds/1
  # PUT  /feeds/1.json
  def update
    @feed = Feed.find(params[:id])

    respond_to do |format|
      if @feed.update_attributes(feed_params)
        format.html { redirect_to @feed, notice: 'Successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed = Feed.find(params[:id])
    @feed.destroy

    respond_to do |format|
      format.html { redirect_to feeds_path }
      format.json { head :no_content }
    end
  end
  
  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def feed_params
    params.require(:feed).permit(:feed_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_form.html.erb
<%= form_for @feed do |f| %>
  <% if @feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= "#{pluralize(@feed.errors.count, "error")} prohibited this feed from being saved:" %></h2>
      <ul>
        <% @feed.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :feed_url %>
    <%= f.text_field :feed_url %>
  </div>
  <p class="actions">
    <%= f.submit 'Save', class: "btn btn-primary" %>
  </p>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing feed</h1>

<%= render partial: 'form' %>

<%= link_to 'Show', @feed %> | <%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<h1>Listing feeds</h1>

<table class="table table-hover" style="width:100%;">
  <thead>
    <tr>
      <th>Title</th>
      <th>URL</th>
      <th>Description</th>
      <th width="200">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td><%= feed.title %></td>
        <td><%= feed.url %></td>
        <td><%= feed.description %></td>
        <td>
          <%= link_to 'Show', feed, :class => 'btn btn-primary' %>
          <%= link_to 'Edit', edit_feed_path(feed), :class => 'btn btn-primary' %>
          <%= link_to 'Destroy', feed, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @feeds if @feeds.present? %>

<br /><%= link_to 'New Feed', new_feed_path, :class => 'btn btn-primary' %>

app/views/feeds/new.html.erb
<h1>New feed</h1>

<%= render partial: 'form' %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/readers.html.erb
<h1>Latest posts</h1>

<div class="list-group">
  <% @posts.each do |post| %>
    <p><%= link_to post.title, post.url, target: "_blank" %></p>
  <% end if @posts.present? %>
</div>

app/views/feeds/show.html.erb
<h1>Feed details</h1>
<p><b>Title:</b><%= @feed.title %></p>
<p><b>URL:</b><%= @feed.url %></p>
<p><b>Description:</b><%= @feed.description %></p>

<%= link_to 'Edit', edit_feed_path(@feed) %> | <%= link_to 'Back', feeds_path %>

<h3>Recent feeds</h3>
<% @feed.entries.each do |entry| %>
  <div style="margin-bottom:10px;">
    <div><%= link_to entry.title, entry.url, target: "_blank" %></div>
    <div><%= entry.published %></div>
  </div>
  <p><%= entry.summary %></p>
<% end if @feed.entries %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "RSS Reader" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all", "data-turbolinks-track" => true %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">RSS Reader</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Feed Readers", readers_feeds_path %></li>
              <li><%= link_to "Add a new feed", new_feed_path %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        
        <div class="span12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; RSS Reader 2014</p>
      </footer>
    </div> <!-- /container -->
  </body>
</html>